micronaut-projects/micronaut-views

src/main/docs/guide/views.adoc
annotate your model POJO with @Introspected to avoid reflection at runtime.
also a workaround for https://github.com/micronaut-projects/micronaut-views/issues/4
=> @Introspected on model POJO

src/main/docs/guide/releaseHistory.adoc, src/main/docs/guide/toc.yml
=> Release history links to github releases

views-core/src/main/resources/META-INF/native-image/io.micronaut.views.csp/native-image.properties
This PR is backward compatible with GraalVM 20.3.0 and fixes the following error:
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
at parsing …
```
=> Initialize class at run-time. Fixes GraalVM 21.1.0

views-pebble/src/main/java/io/micronaut/views/pebble/PebbleEngineFactory.java
Close: https://github.com/micronaut-projects/micronaut-views/pull/236
=> feat: pebble - Added parallel tag support

views-core/src/main/java/io/micronaut/views/ViewsConfiguration.java, views-core/src/main/java/io/micronaut/views/ViewsConfigurationProperties.java, views-core/src/main/java/io/micronaut/views/ViewsRenderer.java, views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java, views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
includes javadoc improvements introduced by @rferreira at https://github.com/micronaut-projects/micronaut-views/pull/261
=> javadoc: copy changes

src/main/docs/guide/breaks.adoc, src/main/docs/guide/views/model/custom.adoc, test-suite/src/test/groovy/views/ModelAndViewSpec.groovy, test-suite/src/test/java/io/micronaut/views/model/ConfigViewModelProcessor.java, test-suite/src/test/java/io/micronaut/views/model/FruitsController.java, test-suite/src/test/resources/views/fruits-processor.vm, views-core/src/main/java/io/micronaut/views/ViewsFilter.java, views-core/src/main/java/io/micronaut/views/model/ViewModelProcessor.java, views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java
Changes introduced by @rferreira to use a generic at `ViewModelProcessor` 
https://github.com/micronaut-projects/micronaut-views/pull/261
Close https://github.com/micronaut-projects/micronaut-views/issues/247
=> BREAKING CHANGE: Typed ViewModelProcessor

test-suite/src/test/groovy/views/NonHTMLViewRendererSpec.groovy, views-core/src/main/java/io/micronaut/views/ViewsRenderer.java, views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java, views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java, views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java, views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java, views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java, views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java, views-velocity/src/main/java/io/micronaut/views/velocity/VelocityViewsRenderer.java
Leave only method taking request ViewsRenderer::render(String, T, HttpRequest)
=> BREAKING CHANGE: del ViewsRenderer::render(String, T)

src/main/docs/guide/views/security/security-model-enhancement.adoc
=> doc: clarify SecurityViewModelProcessor is typed

views-core/src/main/java/io/micronaut/views/csp/CspConfiguration.java
relates to: https://github.com/micronaut-projects/micronaut-aot/issues/25
=> fix. policyDirectives is nullable Optional.ofNullable

views-pebble/src/main/java/io/micronaut/views/pebble/PebbleEngineFactory.java, views-pebble/src/main/java/io/micronaut/views/pebble/PebbleLoader.java, views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java, views-pebble/src/test/groovy/io/micronaut/docs/PebbleController.groovy, views-pebble/src/test/groovy/io/micronaut/docs/PebbleViewsRendererSpec.groovy, views-pebble/src/test/resources/views/text.txt
This commit allows templating of other text files
=> Pebble fixed template name handling

gradle.properties
- project version to 3.2.0-SNAPShOT
- groovy from 3.0.9 to 3.0.10
- micronaut from 3.2.1 to 3.3.4
- use https for micronaut url
- set githubCoreBranch to 3.4.x
=> ci: project version to 3.2.0-SNAPSHOT

test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboViewTest.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboViewTest.kt, test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboViewTest.java, views-core/src/main/java/io/micronaut/views/ViewsFilter.java, views-core/src/main/java/io/micronaut/views/turbo/TurboStream.java, views-core/src/test/groovy/io/micronaut/views/turbo/TurboFrameSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
- Ability to respond TurboFrame and TurboStream from a controller method. Not just a TurboFramge.Builder or TurboStream.Builder
=> fix: turboview ann only if request accepts turbo

src/main/docs/guide/views/turbo/turboFrameView.adoc
Close: https://github.com/micronaut-projects/micronaut-views/issues/401
=> doc: link to turbo frame not turbo stream

gradle.properties, gradle/libs.versions.toml, settings.gradle, test-suite-groovy/build.gradle, test-suite-kotlin/build.gradle, test-suite/build.gradle, views-bom/build.gradle, views-core/build.gradle, views-freemarker/build.gradle, views-handlebars/build.gradle, views-jte/build.gradle, views-pebble/build.gradle, views-rocker/build.gradle, views-soy/build.gradle, views-thymeleaf/build.gradle, views-velocity/build.gradle
Supersedes https://github.com/micronaut-projects/micronaut-views/pull/410
=> Migration to Gradle Version Catalog

gradle.properties
- Project version to 3.5.0-SNAPSHOT
- github core branch to 3.6.x
=> build: Upgrade to Micronaut 3.5.3

gradle/libs.versions.toml, views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
- Deprecate `JteViewsRender::getOutput(Writer`
=> build: bump up jte to 2.0.3

gradle.properties
- Micronaut Framework to 3.5.4
- Micronaut Test to 3.4.0
- groovyVersion 3.0.12
=> build: Micronaut Framework to 3.5.4

src/main/docs/guide/views/templates/jte.adoc, views-jte/build.gradle, views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
=> build: remove unnecessary gg.jte/jte-kotlin dependency

config/accepted-api-changes.json
=> binary compatability fix for deprecation removal

settings.gradle, src/main/docs/guide/toc.yml, src/main/docs/guide/views/security/csp.adoc, src/main/docs/guide/views/templates/soy/soyfeaturesrenaming.adoc
=> Issue 486 - update build plugin to 5.4.0 update adoc files to use configuration snippets

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, settings.gradle, test-suite-groovy/build.gradle, test-suite-kotlin/build.gradle, test-suite/build.gradle, views-core/build.gradle, views-freemarker/build.gradle, views-handlebars/build.gradle, views-jte/build.gradle, views-pebble/build.gradle, views-rocker/build.gradle, views-soy/build.gradle, views-thymeleaf/build.gradle, views-velocity/build.gradle
=> build: plugin to 6.3.3, standardized project names, validation dependency

src/main/docs/guide/views/templates/soy/soyfeaturesrenaming.adoc, test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/RewriteMapProvider.groovy, test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/RewriteMapProviderSpec.groovy, test-suite-groovy/src/test/resources/styles/renaming-map.json, test-suite-kotlin/src/test/kotlin/io/micronaut/docs/soy/RewriteMapProvider.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/docs/soy/RewriteMapProviderTest.kt, test-suite-kotlin/src/test/resources/styles/renaming-map.json, test-suite/src/test/java/io/micronaut/docs/soy/RewriteMapProvider.java, test-suite/src/test/java/io/micronaut/docs/soy/RewriteMapProviderTest.java, test-suite/src/test/resources/styles/renaming-map.json
=> Move `RewriteMapProvider` example to docs examples and add test.

.editorconfig, .github/workflows/graalvm-latest.yml, .github/workflows/gradle.yml, gradle.properties, settings.gradle, test-suite-kotlin/build.gradle
Supersedes #615 to stop micronaut-build force pushing it all the time.
=> Fix java 21

views-fieldset/src/main/java/io/micronaut/views/fields/DefaultFieldGenerator.java, views-fieldset/src/main/java/io/micronaut/views/fields/TrixEditorFormElement.java, views-fieldset/src/main/java/io/micronaut/views/fields/annotations/TrixEditor.java, views-fieldset/src/main/java/io/micronaut/views/fields/render/TrixEditorFormElementRenderer.java, views-fieldset/src/test/java/io/micronaut/views/fields/TrixEditorFormElementTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/TrixEditorFormTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/render/TrixEditorFormElementRendererTest.java
see: https://github.com/basecamp/trix
=> trix editor

views-fieldset/src/test/java/io/micronaut/views/fields/FieldGeneratorTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/InputHiddenFormElementTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/TestUtils.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/EnumAsCheckboxButtonTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/EnumAsRadioButtonTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/EnumDefaultsToSelectTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/EnumOptionFetcherTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/EventCreateFormTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/FormElementFixture.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/LoginFormTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/SaveBoxOfficeClerkFormTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/SignupFormTest.java, views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/TrixEditorFormTest.java
When these fail, you just get a message 'Expected true, but was false'
This is hard to work out a cause for.
This PR pulls out 2 methods for testing anyOf equality AND anyOf instanceof X
=> Make the assertTrue/anyOf assertions more debuggable

test-suite/src/test/java/io/micronaut/views/model/ConfigViewModelProcessor.java, test-suite/src/test/java/views/ModelAndViewTest.java, views-core/src/main/java/io/micronaut/views/DefaultModelAndViewRenderer.java, views-core/src/main/java/io/micronaut/views/DefaultViewsModelDecorator.java, views-core/src/main/java/io/micronaut/views/MediaTypeResolution.java, views-core/src/main/java/io/micronaut/views/ModelAndView.java, views-core/src/main/java/io/micronaut/views/ModelAndViewRenderer.java, views-core/src/main/java/io/micronaut/views/RawModelAndViewMessageBodyHandler.java, views-core/src/main/java/io/micronaut/views/ViewsModelDecorator.java, views-core/src/main/java/io/micronaut/views/model/ViewModelProcessor.java, views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java, views-core/src/main/java/io/micronaut/views/turbo/TurboFrame.java, views-core/src/main/java/io/micronaut/views/turbo/TurboFrameFilter.java
Some nullability annotations
javadoc correction
=> Use generic instead of HTTP Request

views-core/src/main/java/io/micronaut/views/turbo/TurboConfiguration.java, views-core/src/main/java/io/micronaut/views/turbo/TurboConfigurationProperties.java, views-core/src/test/groovy/io/micronaut/views/TurboDisableSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboFrameBuilderHtmlMessageBodyWriterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboFrameFilterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboFrameRendererSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamBuilderMessageBodyWriterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamFilterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamListOfBuilderMessageBodyWriterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamMessageBodyWriterSpec.groovy, views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamRendererSpec.groovy
By setting micronaut.views.turbo.enabled=false
=> make possible to disable the turbo integration

src/main/docs/guide/breaks.adoc, views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
=> major: remove deprecated methods

views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java
=> Don't rely on SecurityService for the SecurityViewModelProcessor

.github/workflows/gradle.yml, .github/workflows/release.yml
Updating https://github.com/micronaut-projects/micronaut-views/pull/748 but for the 5.1.x branch (incase we want a new version in Micronaut 4.3.x)
=> Update common files

.github/workflows/gradle.yml, .github/workflows/release.yml
Merges the SLSA update from 5.1.x into 5.2.x
=> Mergeup 5.1.x
