micronaut-projects/micronaut-views

views-velocity/build.gradle
views-velocity/src/main/java/io/micronaut/views/velocity/VelocityGraalSupport.java

Generate the meta-information needed by GraalVM. This was done previously in our test application https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/velocity/src/main/java/example/micronaut/Application.java#L6-L21 but I forgot to move that code here.

Add support for GraalVM

---

views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerController.groovy
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
views-freemarker/src/test/resources/views/invalid.ftl

With this PR, when there is an error in a view, the right error message is displayed:
```
Caused by: freemarker.core.ParseException: Syntax error in template "invalid.ftl" in line 23, column 8:
Unexpected end of file reached. You have an unclosed #if.
```

Catch the right exception. Fixes #11

---

gradle.properties

[Pebble 3.1.5 release notes](https://github.com/PebbleTemplates/pebble/releases/tag/3.1.5). It is a patch release but it seems to contain new feature. Apparently no breaking changes.

build: bump up pebble to 3.1.5

---

gradle.properties

[Freemarker 2.3.31 - Release notes](https://freemarker.apache.org/docs/versions_2_3_31.html)

build: bump up freemarker from 2.3.30 to 2.3.31

---

gradle.properties

Release notes don't say anything about what's new. [2021-02-01](https://github.com/google/closure-templates/releases/tag/release-2021-02-01). I don't think there are breaking changes based on the [commits list](https://github.com/google/closure-templates/compare/release-2021-02-01...master)

build: bump up soy to 2021-02-01

---

views-core/src/main/resources/META-INF/native-image/io.micronaut.views.model.security/native-image.properties

This PR fixed the following warning when creating a GraalVM native image: 
```
[views-freemarker:203]    classlist:   3,692.05 ms,  0.96 GB
[views-freemarker:203]        (cap):     507.48 ms,  0.96 GB
[views-freemarker:203]        setup:   2,309.91 ms,  0.96 GB
Warning: class initialization of class io.micronaut.views.model.security.$SecurityViewModelProcessor$Definition failed with exception java.lang.NoClassDefFoundError: io/micronaut/security/utils/SecurityService. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.views.model.security.$SecurityViewModelProcessor$Definition to explicitly request delayed initialization of this class.
...
...
```

Fix GraalVM warning

---

src/main/docs/guide/breaks.adoc
test-suite/src/test/groovy/views/NonHTMLViewRendererSpec.groovy
test-suite/src/test/resources/views/books.vm
views-core/src/main/java/io/micronaut/views/ViewsFilter.java
views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerController.groovy
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java
views-rocker/src/test/groovy/io/micronaut/docs/RockerController.groovy
views-rocker/src/test/groovy/io/micronaut/docs/RockerViewRendererSpec.groovy
views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
views-velocity/src/main/java/io/micronaut/views/velocity/VelocityViewsRenderer.java
views-velocity/src/test/groovy/io/micronaut/docs/VelocityController.groovy
views-velocity/src/test/groovy/io/micronaut/docs/VelocityViewRendererSpec.groovy

- Removes the @Produces(MediaType.TEXT_HTML) annotation from ViewsRenderer
Close: https://github.com/micronaut-projects/micronaut-views/issues/167
Close: https://github.com/micronaut-projects/micronaut-views/issues/159

BREAKING CHANGE: typed ViewsRenderer

---

views-core/src/main/java/io/micronaut/views/DefaultViewsRendererLocator.java
views-core/src/main/java/io/micronaut/views/ViewsFilter.java
views-core/src/main/java/io/micronaut/views/ViewsRendererKey.java
views-core/src/main/java/io/micronaut/views/ViewsRendererLocator.java

This extracts the location of `ViewsRenderer` to its own class. Moreover, it uses a concurrent hash map to avoid recalculation which views renderer should be used each time.

BREAKING CHANGE: extract ViewsRenderLocator

---

views-core/src/main/java/io/micronaut/views/ViewUtils.java
views-core/src/test/groovy/io/micronaut/views/ViewUtilsSpec.groovy

`ViewUtils.normalizeFile()` javadoc says 
> supports extensions that do and do not begin with a "."
This change fixes it so it actually does.

fix dot handling in normalizeFile

---

views-freemarker/src/main/resources/META-INF/native-image/io.micronaut.views.freemarker/native-image.properties
views-freemarker/src/main/resources/META-INF/native-image/io.micronaut.views.freemarker/resource-config.json
views-handlebars/src/main/resources/META-INF/native-image/io.micronaut.views.handlebars/native-image.properties
views-handlebars/src/main/resources/META-INF/native-image/io.micronaut.views.handlebars/resource-config.json
views-pebble/src/main/resources/META-INF/native-image/io.micronaut.views.pebble/native-image.properties
views-thymeleaf/src/main/resources/META-INF/native-image/io.micronaut.views.thymeleaf/native-image.properties

Build time initialization is not really recommended. This PR removed it because it also not necessary anymore.

graalvm: remove build time initiazation

---

test-suite/src/test/java/io/micronaut/views/model/UnmodifiableFruitsController.java
test-suite/src/test/java/views/UnmodifiableModelAndViewTest.java
test-suite/src/test/resources/views/unmodifiablefruits.vm
views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java

The SecurityViewModelProcessor will fail the request and throw an UnsupportedOperationException
if an unmodifiable Map is used as the view model for a request.
This change catches that error, and logs an error explaining the issue, and showing the user
the path that caused the error to occur.
Fixes #336

bug: ViewModelProcessor does not handle immutable maps

---

views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/MessageSourceMessageResolver.java
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/MicronautThymeMessageResolverSpec.groovy
views-thymeleaf/src/test/resources/views/thymeleaf/sample_int_params.html

I got this crash when using thymeleaf and internationalization messages with an integer: 
```
subscriber.calltoaction.count=Join {0} subscribers!
```
```
aused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
at io.micronaut.views.thymeleaf.MessageSourceMessageResolver.resolveMessage(MessageSourceMessageResolver.java:62)
at org.thymeleaf.context.AbstractEngineContext.getMessage(AbstractEngineContext.java:134)
at org.thymeleaf.standard.expression.MessageExpression.executeMessageExpression(MessageExpression.java:265)
at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:69)
at …
```

fix: protects against object not being of type String

---

views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
views-pebble/src/test/groovy/io/micronaut/docs/PebbleController.groovy
views-pebble/src/test/groovy/io/micronaut/docs/PebbleViewsRendererSpec.groovy
views-pebble/src/test/resources/i18n/messages_de.properties
views-pebble/src/test/resources/i18n/messages_en.properties
views-pebble/src/test/resources/i18n/messages_it.properties
views-pebble/src/test/resources/views/i18n.txt

See https://github.com/micronaut-projects/micronaut-views/issues/358
This makes Pebble regard the `Accept-Language` header.
Tests included. I started with a red test and fixed it. It was a one-liner in the main code.

Pass Locale to Pebble

---

test-suite/src/test/java/views/NonHTMLViewRendererTest.java
views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
views-freemarker/src/test/groovy/io/micronaut/views/freemarker/FreemarkerViewRenderNullableRequestSpec.groovy
views-freemarker/src/test/resources/views/tim.ftl
views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
views-handlebars/src/test/groovy/io/micronaut/views/handlebars/HandlebarsViewRenderNullableRequestSpec.groovy
views-handlebars/src/test/resources/views/tim.hbs
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
views-jte/src/test/groovy/io/micronaut/jte/JteViewRenderNullableRequestSpec.groovy
views-jte/src/test/resources/views/tim.jte
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
views-pebble/src/test/groovy/io/micronaut/views/pebble/PebbleViewRenderNullableRequestSpec.groovy
views-pebble/src/test/resources/views/tim.html
views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java
views-rocker/src/test/groovy/io/micronaut/views/rocker/RockerViewRenderNullableRequestSpec.groovy
views-rocker/src/test/resources/views/tim.rocker.html
views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
views-soy/src/test/groovy/io/micronaut/views/soy/SoyViewRenderNullableRequestSpec.groovy
views-soy/src/test/resources/views/home.soy
views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/WebContext.java
views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/WebEngineContext.java
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderNullableRequestSpec.groovy
views-thymeleaf/src/test/resources/views/tim.html
views-velocity/src/test/groovy/io/micronaut/views/velocity/VelocityViewRenderNullableRequestSpec.groovy
views-velocity/src/test/resources/views/tim.vm

This makes the `ViewsRenderer` HTTP Request parameter nullable. It is used for example, in the Micronaut Email module and you may use it in places where you don't have an HTTP Request (For example, in a cron job).

refactor: make HttpRequest parameter in ViewsRenderer nullable

---

gradle.properties
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfiguration.java
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfigurationProperties.java
views-jte/src/main/java/io/micronaut/views/jte/JteWritable.java
views-jte/src/main/java/io/micronaut/views/jte/PlainJteViewsRenderer.java
views-jte/src/test/groovy/io/micronaut/docs/BinaryJteViewRendererSpec.groovy
views-jte/src/test/groovy/io/micronaut/docs/JteViewRendererSpec.groovy
views-jte/src/test/groovy/io/micronaut/docs/WriterJteViewRendererSpec.groovy

Update JTE to latest version.
Support for 'binary static content' in JTE. This pre-converts Strings to UTF-8 bytes to reduce work during rendering.

support binary static content in JTE

---

src/main/docs/guide/views/templates/jte.adoc
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfiguration.java
views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfigurationProperties.java
views-jte/src/main/java/io/micronaut/views/jte/JteWritable.java
views-jte/src/test/groovy/io/micronaut/docs/DynamicRendererSpec.groovy
views-jte/src/test/groovy/io/micronaut/docs/JteController.groovy
views-jte/src/test/groovy/io/micronaut/jte/JteViewRenderNullableRequestSpec.groovy
views-jte/src/test/jte/dynamic.jte

This is not completely polished but I wanted to share it for feedback.
For JTE - modifies where templates are loaded from when 'dynamic' is enabled, so that it can pick up 'src' changes.
TODO - still need to update the docs.

JTE - support dynamic template loading from src path

---

views-freemarker/src/test/resources/views/home.ftl
views-freemarker/src/test/resources/views/invalid.ftl
views-thymeleaf/src/test/groovy/io/micronaut/docs/ViewsController.groovy

- make ViewsController.groovy compatible with Java
- remove license code from freemarker files
Docs include parts from `ViewsController.groovy` but say that it is a Java file. With this change the code is less confusing for someone not used to Groovy syntax and is **almost** compatible with Java - there are still missing semicolons.
Also the license header is removed from freemarker files as it clutters the docs (other template engines do not have license headers).

Polish docs.

---

build.gradle
config/accepted-api-changes.json
config/checkstyle/checkstyle.xml
gradle/libs.versions.toml
settings.gradle
test-suite-groovy/build.gradle
test-suite-kotlin/build.gradle
test-suite/build.gradle
views-core/build.gradle
views-freemarker/build.gradle
views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRendererConfigurationProperties.java
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
views-handlebars/build.gradle
views-jte/build.gradle
views-pebble/build.gradle
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleConfigurationProperties.java
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleEngineFactory.java
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleLoader.java
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
views-pebble/src/main/java/io/micronaut/views/pebble/package-info.java
views-rocker/build.gradle
views-soy/build.gradle
views-soy/src/test/resources/views/home.soy
views-thymeleaf/build.gradle
views-velocity/build.gradle

Migrate to build plugins 6.1.1, update version catalog and dependencies to correspond to changed bom/platform architecture, misc build fixes, fix changed package names in src for pebble library.

Migrate to build plugins 6.1.1, other fixes

---

views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy

The test fails because in Micronaut 4 [`FreemarkerViewsRendererConfigurationProperties::setSettings`](https://github.com/micronaut-projects/micronaut-views/blob/master/views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRendererConfigurationProperties.java#L138) is not invoked. We have to identify if there is a bug in core.

uncomment test

---

gradle/libs.versions.toml
test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/CustomSoyFileSetProvider.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/SoySpec.groovy
views-core/src/main/java/io/micronaut/views/ViewsFilter.java
views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
views-handlebars/src/test/groovy/io/micronaut/docs/HandlebarsController.groovy
views-handlebars/src/test/groovy/io/micronaut/docs/HandlebarsViewsRendererSpec.groovy
views-handlebars/src/test/resources/views/badsyntax.hbs
views-jte/src/test/groovy/io/micronaut/docs/JteController.groovy
views-jte/src/test/groovy/io/micronaut/docs/JteViewRendererSpec.groovy
views-jte/src/test/resources/views/badsyntax.jte
views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
views-pebble/src/test/groovy/io/micronaut/docs/PebbleController.groovy
views-pebble/src/test/groovy/io/micronaut/docs/PebbleViewsRendererSpec.groovy
views-pebble/src/test/resources/views/badsyntax.html
views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
views-soy/src/test/groovy/io/micronaut/docs/BadSyntaxSoyController.groovy
views-soy/src/test/groovy/io/micronaut/docs/BadSyntaxSoyFileSetProvider.groovy
views-soy/src/test/groovy/io/micronaut/docs/SoySauceViewRendererBadsyntaxSpec.groovy
views-soy/src/test/groovy/io/micronaut/views/soy/SoyViewRenderNullableRequestSpec.groovy
views-soy/src/test/resources/views/badsyntax.soy
views-velocity/src/main/java/io/micronaut/views/velocity/VelocityViewsRenderer.java
views-velocity/src/test/groovy/io/micronaut/docs/VelocityController.groovy
views-velocity/src/test/groovy/io/micronaut/docs/VelocityViewRendererSpec.groovy
views-velocity/src/test/resources/views/badsyntax.vm

fixes #478
This was more of a problem than that described by the original issue. The root problem is that template compilation was occurring after `ViewsFilter.doFilter()` returned so `Flux.error()` wasn't returned when it should have been. That resulted in the template rendering endpoints stalling and eventually raising a `ReadTimeoutException`. 
I have changed all the templating engine implementations to parse/compile the template before `doFilter()` returns so that it fails fast. I also made them more consistent in failure behavior (e.g. using `ViewRenderingException` as the cause). The one thing I'm not certain about is if it will be a problem with reactive response for large/complex templates.
I added/revised tests to make sure expected `HttpClientException` exceptions on failed …

Rendering failure with ViewRenderingException fails with ReadTimeoutException

---

test-suite-thymeleaf-fieldset/src/test/resources/views/fieldset/form.html
views-fieldset-tck/src/main/java/io/micronaut/views/fields/tck/FormEncTypeRenderTest.java
views-fieldset/src/main/java/io/micronaut/views/fields/Fieldset.java
views-fieldset/src/main/java/io/micronaut/views/fields/Form.java
views-fieldset/src/main/java/io/micronaut/views/fields/constraints/EnctypePostRequired.java
views-fieldset/src/main/java/io/micronaut/views/fields/constraints/EnctypePostRequiredValidator.java
views-fieldset/src/main/java/io/micronaut/views/fields/constraints/FormMessages.java
views-fieldset/src/main/java/io/micronaut/views/fields/constraints/package-info.java
views-fieldset/src/main/java/io/micronaut/views/fields/messages/Message.java
views-fieldset/src/test/java/io/micronaut/views/fields/FormTest.java
views-fieldset/src/test/java/io/micronaut/views/fields/messages/MessageTest.java

feat: Add enctype to Form

---

views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderFragment.groovy
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderFragmentSpec.groovy
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderNullableRequestSpec.groovy
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/WriteableUtils.groovy
views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/web/LinkTestController.groovy
views-thymeleaf/src/test/resources/views/fragment.html

This PR adds the ability to return a thymeleaf fragment in a view instead of the whole template. Very useful for tools like [htmx.org](https://htmx.org).
This code takes inspiration from the thymeleaf spring integration, found [here](https://github.com/thymeleaf/thymeleaf-spring/blob/f078508ce7d1d823373964551a007cd35fad5270/thymeleaf-spring6/src/main/java/org/thymeleaf/spring6/view/ThymeleafView.java#L269)

Add ability to render thymeleaf fragments

---

gradle.properties
gradle/libs.versions.toml

The 5.1.x branch seems to have got a few 5.2.x things on it.
This PR resets the versions for the 5.1.x branch (which was in micronaut 4.3.7)

build: Fix the 5.1.x branch
